# Generated by Django 2.0.4 on 2018-04-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('card_image', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('deactivate_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gather',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AddField(
            model_name='card',
            name='gather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gather'),
        ),
    ]
