# Generated by Django 2.0.4 on 2018-04-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='deactivate_at',
            field=models.DateField(),
        ),
    ]
